version: '3.9'

services:
  app:
    image: henahax/amoeben-indikator:latest
    restart: always
    environment:
      - HOST=0.0.0.0
      - PORT=4321
      - DATABASE_URL=postgres://postgres:postgres@db:5432/test
    ports:
      - 4321:4321
    depends_on:
      - db
    entrypoint: ["./entrypoint.sh"]
  db:
    image: postgres
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      - POSTGRES_DB=test
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
