version: '3.8'
services:
  app:
    image: henahax/amoeben-indikator:latest
    container_name: amoeben-indikator
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
      - PORT=3000
      - DATABASE_URL=postgres://root:Holz1337@db:5432/amoeben-indikator
    ports:
      - 8080:3000
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:latest
    container_name: amoeben-indikator-db
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=Holz1337
      - POSTGRES_DB=amoeben-indikator
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U root -d amoeben-indikator" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  postgres-data:
    name: amoeben-indikator-data
