version: '2.1'
services:
  nginx:
    image: henahax/amoeben-indikator:latest
    container_name: amoeben-indikator
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
      - DATABASE_URL=local.db
    ports:
      - 8080:3000
    volumes:
      - amoeben-indikator:/
    restart: unless-stopped
