version: '3.9'
services:
  app:
    image: henahax/amoeben-indikator:latest
    container_name: amoeben-indikator
    hostname: amoeben-indikator
    restart: always
    environment:
      - HOST=0.0.0.0
      - PORT=4321
      - DATABASE_URL=postgres://postgres:postgres@db:5432/test
    ports:
      - 8083:4321
    depends_on:
      - db
    entrypoint: ["/app/entrypoint.sh"]
    working_dir: /app
  db:
    image: postgres:latest
    container_name: amoeben-indikator-db
    hostname: amoeben-indikator-db
    restart: always
    shm_size: 128mb
    environment:
      - POSTGRES_DB=test
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
  adminer:
    image: adminer
    container_name: amoeben-indikator-admin
    hostname: amoeben-indikator-admin
    restart: always
    ports:
      - 8084:8080
