services:
  amoeben-indikator-db:
    image: postgres
    container_name: amoeben-indikator-db
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: Holz1337
      POSTGRES_DB: amoeben-indikator
    volumes:
      - local_pgdata:/var/lib/postgresql/data
  amoeben-indikator-admin:
    image: dpage/pgadmin4
    container_name: amoeben-indikator-pgadmin
    restart: unless-stopped
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: mail@henahax.de
      PGADMIN_DEFAULT_PASSWORD: Holz1337
    volumes:
      - pgadmin-data:/var/lib/pgadmin
volumes:
  local_pgdata:
  pgadmin-data:
