name: CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']
  workflow_dispatch:

jobs:
  Docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: latest

      - name: Setup git config
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "${{ secrets.EMAIL }}"

      - name: Install dependencies
        run: npm ci

      - name: Build application
        run: npm run build

      - name: Save version
        id: version
        run: echo ::set-output name=tag::$(echo $(node -p -e "require('./package.json').version"))

      - name: Increase version
        run: npm version patch

      - name: Push new version
        run: git push

      - name: Login to DockerHub
        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Build Docker image
        run: |
          docker build . \
            --file Dockerfile \
            --tag henahax/amoeben-indikator:latest \
            --tag henahax/amoeben-indikator:${{ steps.version.outputs.tag }}

      - name: Push to Docker Hub
        run: |
          docker push henahax/amoeben-indikator:latest
          docker push henahax/amoeben-indikator:${{ steps.version.outputs.tag }}
